id: I00045399
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-e19a
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 16:35:24.691142+00:00
last_modified: 2023-09-29 16:35:24.691151+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17934
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17934
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟ་ནག་རྣམ་འགྲེལ། ལེའུ་དང་པོ།
  languages:
  - bo
  author: རྟ་ནག་པ་དགེ་འདུན་བློ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9560950625766474
  ocr_word_median_confidence_index: 0.9948614
bases:
  I8LS17949:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17949
      total_pages: 1446
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17949.txt
    statistics:
      ocr_word_median_confidence_index: 0.9948614
      ocr_word_mean_confidence_index: 0.9560950625766474
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
